- name: Variables
  hosts:  local
  connection: local
  vars:
    PROJECT: "QBE"
    ENVIRONMENT: "PROD"

  tasks:
  - name: Print the Variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }} environment is {{ ENVIRONMENT }}"