- name: Variables
  hosts:  local
  connection: local
  vars_files:
  - project.yaml 


  tasks:
  - name: Print the Variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }} environment is {{ ENVIRONMENT }}"