- name: Variables
  hosts:  local
  connection: local
  vars_prompt:
  - name: project
    prompt: What is your project?
    private: false

  - name: environment
    prompt: What is your environment?
    private: false



  tasks:
  - name: Print the Variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }} environment is {{ ENVIRONMENT }}"