- name: variables
  hosts: localhost
  connection: localhost
  vars_prompt:
  - name: PROJECT
    prompt: Please enter the PROJECT
    private: false

  - name: ENVIRONMENT
    prompt: Please enter the ENVIRONMENT
    private: false

  - name: COMPONENT
    prompt: Please enter the COMPONENT
    private: false

  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }}, environment is {{ ENVIRONMENT }}, component is {{ COMPONENT }}"