- name: Variables
  hosts:  local
  connection: local
  vars_prompt:
  - name: PROJECT
    prompt: What is your PROJECT?
    private: false

  - name: ENVIRONMENT
    prompt: What is your ENVIRONMENT?
    private: false



  tasks:
  - name: Print the Variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }} environment is {{ ENVIRONMENT }}"