- name: variables
  hosts: web
  become: yes

  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "project is {{ PROJECT }}, environment is {{ ENVIRONMENT }}, component is {{ COMPONENT }}"
