- name: variables
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  
  vars_files:
  - project.yaml

  vars_prompt:
  - name: GREET
    prompt: "What is your GREET?"
    private: false

  tasks:
  - name: task GREET
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "{{ GREET }}"
  