- name: conditions
  hosts: local
  connection: local
  vars_promt:
  - name: my_number
    prompt: "What is your number?"
    private: false

  tasks:
  - name: print the conditions
    ansible.builtin.debug:
      msg : "Given number is less than {{ my_number }}"
    when: my_number <= 15

  - name: print the conditions
    ansible.builtin.debug:
      msg : "Given number is greater than {{ my_number }}"
    when: my_number > 15