- name: conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: What is your my_number?
    private: false

  tasks:
  - name: print less than 100
    ansible.builtin.debug:
      msg : "Given number is less than {{ my_number }}"
    when: my_number |int <= 100

  - name: print greater than 100
    ansible.builtin.debug:
      msg : "Given number is greater than {{ my_number }}"
    when: my_number | int > 100