- name: install based on os family
  hosts: web
  become: yes
  tasks:
  - name: install the package dnf
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family| string = "RedHat"

  - name: install the package
    ansible.builtin.apt:
      name: ubuntu
      state: present
    when: ansible_os_family="Debain"