- name: Install multiple applications
  hosts: web
  become: yes
  tasks:
  - name: Install multiple applications
    ansible.builtin.package:
      name: {{ item }}
      state: installed
    loop:
    - gcc
    - git
    - zip

  # - name: Install multiple applications
  #   ansible.builtin.package:
  #     name: git
  #     state: installed

  # - name: Install multiple applications
  #   ansible.builtin.package:
  #     name: zip
  #     state: installed


