- name: shell modules
  hosts: web
  tasks:
  - name:  command
    ansible.builtin.command: ls -l

  # - name: command module
  #   ansible.builtin.command: ls -l >> /tmp
  #   register: command_result

  - name: shell module
    ansible.builtin.shell: ls -l >> /tmp/output.txt


  - name: print the command result
    ansible.builtin.debug:
      msg: "{{ command_result }}"

