172.31.32.209

[web]
172.31.32.209

[backend]
172.31.32.209

[mysql]
172.31.32.209


[expense:children]
backend
mysql
web

[local]
localhost 

[local:vars]
PROJECT = "QBE insurance"
ENVIRONMENT = "prod"
COMPONENT = "mysql"